name = "hex-roots-mathlib"
defaultTargets = ["HexRootsMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexRoots"
git = "https://github.com/leanprover/hex-roots.git"
rev = "1cbee8873adc3c6587a00aa288f675be6d105818"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "db6441e818dd3a21e99bd7bf7a1b53291a140207"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexRootsMathlib"

[[lean_lib]]
name = "HexRootsMathlibTests"
globs = ["HexRootsMathlib.Examples"]
