name = "hex-roots-mathlib"
defaultTargets = ["HexRootsMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexRoots"
git = "https://github.com/leanprover/hex-roots.git"
rev = "5de271feb738cd92d96b8140ba7a9bac2f245d3d"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "d9b7ba1f1ef5bc456f9b7467f694b940d5e5200a"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexRootsMathlib"

[[lean_lib]]
name = "HexRootsMathlibTests"
globs = ["HexRootsMathlib.Examples"]
