name = "hex-roots-mathlib"
defaultTargets = ["HexRootsMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexRoots"
git = "https://github.com/leanprover/hex-roots.git"
rev = "b2c9d4656f2a9e8d5a98e231ba89ed02b773e7b8"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "c5af699aa17a8360a0ed414d9826b6a90518f6c9"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.2"

[[lean_lib]]
name = "HexRootsMathlib"

[[lean_lib]]
name = "HexRootsMathlibTests"
globs = ["HexRootsMathlib.Examples"]
