/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import Mathlib.RingTheory.Polynomial.Vieta
public import Mathlib.Analysis.Complex.Basic
public import Mathlib.Algebra.Order.BigOperators.GroupWithZero.Multiset

public section

/-!
# Taylor tails from remote roots

This Mathlib-only module bounds the elementary-symmetric coefficient tail of
a product whose roots stay away from the expansion centre.  It is the
combinatorial estimate behind the degree-dependent Pellet converse.
-/

open Finset

namespace HexRootsMathlib

noncomputable section

private theorem norm_multiset_prod (s : Multiset ℂ) :
    ‖s.prod‖ = (s.map norm).prod := by
  induction s using Multiset.induction_on with
  | empty => simp
  | @cons z s ih => simp [ih]

/-- If every entry of a multiset has norm at most `B`, its `k`-th elementary
symmetric function has norm at most `choose(card, k) * B^k`. -/
theorem norm_esymm_le {s : Multiset ℂ} {B : ℝ}
    (hs : ∀ z ∈ s, ‖z‖ ≤ B) (k : ℕ) :
    ‖s.esymm k‖ ≤ (s.card.choose k : ℝ) * B ^ k := by
  rw [Multiset.esymm]
  calc
    ‖((s.powersetCard k).map Multiset.prod).sum‖ ≤
        (((s.powersetCard k).map Multiset.prod).map norm).sum :=
      norm_multiset_sum_le _
    _ = ((s.powersetCard k).map fun t => ‖t.prod‖).sum := by
      rw [Multiset.map_map]
      rfl
    _ ≤ ((s.powersetCard k).map fun _ => B ^ k).sum := by
      apply Multiset.sum_map_le_sum_map
      intro t ht
      have htcard : t.card = k := (Multiset.mem_powersetCard.mp ht).2
      calc
        ‖t.prod‖ = (t.map norm).prod := norm_multiset_prod t
        _ ≤ (t.map fun _ => B).prod := by
          apply Multiset.prod_map_le_prod_map₀
          · intro z hz
            exact norm_nonneg z
          · intro z hz
            exact hs z <| Multiset.mem_of_le
              (Multiset.mem_powersetCard.mp ht).1 hz
        _ = B ^ t.card := by simp
        _ = B ^ k := by rw [htcard]
    _ = (s.card.choose k : ℝ) * B ^ k := by
      simp [Multiset.card_powersetCard, nsmul_eq_mul]

/-- The positive-degree elementary-symmetric tail is bounded by the binomial
tail generated by a uniform norm bound. -/
theorem esymm_tail_le {s : Multiset ℂ} {B ρ : ℝ} (hρ : 0 ≤ ρ)
    (hs : ∀ z ∈ s, ‖z‖ ≤ B) :
    (∑ k ∈ (Finset.range (s.card + 1)).erase 0,
        ‖s.esymm k‖ * ρ ^ k) ≤
      (1 + ρ * B) ^ s.card - 1 := by
  let n := s.card
  have hterms :
      (∑ k ∈ (Finset.range (n + 1)).erase 0,
          ‖s.esymm k‖ * ρ ^ k) ≤
        ∑ k ∈ (Finset.range (n + 1)).erase 0,
          (n.choose k : ℝ) * (ρ * B) ^ k := by
    apply Finset.sum_le_sum
    intro k hk
    calc
      ‖s.esymm k‖ * ρ ^ k ≤
          ((n.choose k : ℝ) * B ^ k) * ρ ^ k := by
        gcongr
        exact norm_esymm_le hs k
      _ = (n.choose k : ℝ) * (ρ * B) ^ k := by
        rw [mul_pow]
        ring
  have hbinomial :
      (∑ k ∈ Finset.range (n + 1),
          (n.choose k : ℝ) * (ρ * B) ^ k) =
        (1 + ρ * B) ^ n := by
    calc
      (∑ k ∈ Finset.range (n + 1),
          (n.choose k : ℝ) * (ρ * B) ^ k) =
          ∑ k ∈ Finset.range (n + 1),
            (ρ * B) ^ k * 1 ^ (n - k) * (n.choose k : ℝ) := by
        apply Finset.sum_congr rfl
        intro k hk
        simp [mul_comm]
      _ = (ρ * B + 1) ^ n := (add_pow (ρ * B) 1 n).symm
      _ = (1 + ρ * B) ^ n := by rw [add_comm]
  have hzero : (0 : ℕ) ∈ Finset.range (n + 1) := by simp
  rw [← Finset.sum_erase_add _ _ hzero] at hbinomial
  simp only [Nat.choose_zero_right, Nat.cast_one, pow_zero, mul_one] at hbinomial
  change (∑ k ∈ (Finset.range (n + 1)).erase 0,
      ‖s.esymm k‖ * ρ ^ k) ≤ (1 + ρ * B) ^ n - 1
  exact hterms.trans_eq (eq_sub_of_add_eq hbinomial)

/-- If every remote root has norm at least `d`, the normalized coefficient
tail is bounded by `(1 + ρ / d)^n - 1`. The next completeness layer connects
this elementary-symmetric data to the coefficients of the normalized product
`∏ z, (1 - X / z)`. -/
theorem remote_tail_le {s : Multiset ℂ} {d ρ : ℝ} (hd : 0 < d)
    (hρ : 0 ≤ ρ) (hs : ∀ z ∈ s, d ≤ ‖z‖) :
    (∑ k ∈ (Finset.range (s.card + 1)).erase 0,
        ‖(s.map Inv.inv).esymm k‖ * ρ ^ k) ≤
      (1 + ρ / d) ^ s.card - 1 := by
  have hinv : ∀ z ∈ s.map Inv.inv, ‖z‖ ≤ d⁻¹ := by
    intro z hz
    obtain ⟨w, hw, rfl⟩ := Multiset.mem_map.mp hz
    rw [norm_inv]
    exact (inv_le_inv₀ (hd.trans_le (hs w hw)) hd).2 (hs w hw)
  have htail := esymm_tail_le (s := s.map Inv.inv) (B := d⁻¹)
    (ρ := ρ) hρ hinv
  simpa only [Multiset.card_map, div_eq_mul_inv] using htail

end

end HexRootsMathlib
